// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;

namespace CsBindgen
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "agl.dll";

        [DllImport(__DllName, EntryPoint = "compile_csharp", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* compile_csharp(ushort* utf16_str, int utf16_len, Mode mode);


    }


    public enum Mode
    {
        PSX,
        N64,
    }


}
    